export const ADD_DOC_LIST = 'ADD_DOC_LIST';
export const REMOVE_DOC = 'REMOVE_DOC';

export const SELECT_DOCUMENTS = 'SELECT_DOCUMENTS';
export const REMOVE_DOCUMENT = 'REMOVE_DOCUMENT';
export const LOAD_DOCUMENT = 'LOAD_DOCUMENT';
export const DRAG_FIELD = 'DRAG_FIELD';
export const ADD_FIELD = 'ADD_FIELD';

export const ADD_DOCUMENT_TO_SIGN = 'ADD_DOCUMENT_TO_SIGN';
export const ADD_DOCUMENT_TO_SIGN_FAIL = 'ADD_DOCUMENT_TO_SIGN_FAIL';

export const UPDATE_DOCUMENT_TO_SIGN = 'ADD_DOCUMENT_TO_SIGN';
export const UPDATE_DOCUMENT_TO_SIGN_FAIL = 'ADD_DOCUMENT_TO_SIGN_FAIL';
