export const DOCUMENT_GET_PAGE_REQUEST = "DOCUMENT_GET_PAGE_REQUEST";
export const DOCUMENT_GET_PAGE_SUCCESS = "DOCUMENT_GET_PAGE_SUCCESS";
export const DOCUMENT_GET_PAGE_FAIL = "DOCUMENT_GET_PAGE_FAIL";