export const DOCUMENT_GET_PAGE_REQUEST = "DOCUMENT_GET_PAGE_REQUEST";
export const DOCUMENT_GET_PAGE_SUCCESS = "DOCUMENT_GET_PAGE_SUCCESS";
export const DOCUMENT_GET_PAGE_FAIL = "DOCUMENT_GET_PAGE_FAIL";

export const GET_DOCUMENT_REQUEST = "GET_DOCUMENT_REQUEST";
export const GET_DOCUMENT_SUCCESS = "GET_DOCUMENT_SUCCESS";
export const GET_DOCUMENT_FAIL = "GET_DOCUMENT_FAIL";