export const SAVE_WEBVIEWER_INSTANCE = "SAVE_WEBVIEWER_INSTANCE";

export const LOAD_DOCUMENT = "LOAD_DOCUMENT";
export const SET_CURRENT_DOCUMENT = "SET_CURRENT_DOCUMENT";
export const SET_DROP_POINT = "SET_DROP_POINT";
export const APPLY_FIELDS = "APPLY_FIELDS";
